server:
  port: 7012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: exercise

sai:
  name:
    first_name: Himanshu
    lastname: Salgaonkar
  mail: mail1,mail2