server:
  port: 7013

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:7000/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: yoga

management:
  security:
    enabled: false