server:
  port: 7021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
    instance:
      preferIpAddress: true

spring:
  application:
    name: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/sai?autoReconnect=true
    username: root
    password: root
#  driver-class-name=com.mysql.jdbc.Driver
#
#    spring.datasource.
#    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect